/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.yc407.battleship;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;
import java.io.StringReader;

public class App {

  final Board<Character> theBoard;
  final BoardTextView view;
  final BufferedReader inputReader;
  final PrintStream out;
  final AbstractShipFactory<Character> shipFactory;

  // public AbstractShipFactory<Character> shipFactory(){
  // return new V1ShipFactory();
  // }

  public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {
    this.theBoard = theBoard;
    this.view = new BoardTextView(theBoard);
    this.inputReader = new BufferedReader(inputSource);
    this.out = out;
    this.shipFactory = new V1ShipFactory();
  }

  public Placement readPlacement(String prompt) throws IOException {
    out.println(prompt);
    String s = inputReader.readLine();
    return new Placement(s);
  }

  public void doOnePlacement() throws IOException {

    String s = "Where would you like to put your ship?";
    //Ship<Character> ship = new RectangleShip<Character>(readPlacement(s).getCoordinate(), 's', '*');
    Ship<Character> ship = shipFactory.makeDestroyer(readPlacement(s));
    theBoard.tryAddShip(ship);
    out.print(view.displayMyOwnBoard());
  }

  public static void main(String[] args) throws IOException {

    Board<Character> b = new BattleShipBoard<Character>(10, 20);
    InputStream in = System.in;
    InputStreamReader isr = new InputStreamReader(in);
    App app = new App(b, isr, System.out);
    app.doOnePlacement();
  }
}
